version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    # 🚫 Remove volume in prod
    volumes: []  

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules  # ✅ Prevents volume override

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
